import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Alert, Button, Card, Empty, Form, Input, Layout, List, Select, Space, Spin, Tag, Typography } from 'antd';
import { Navigate, useNavigate, useSearchParams } from 'react-router-dom';

import { createFeedbackItem, listFeedbackItems, type FeedbackListResponse } from '@/api/feedback';
import { getAccessToken } from '@/api/session';

const { Header, Content, Footer } = Layout;
type FeedbackForm = { case_id?: string; resource_type: 'case' | 'query_run'; resource_id: string; location_key?: string; error_type: 'citation_error' | 'policy_scope_error' | 'risk_rule_error' | 'procedure_error' | 'other'; description: string };
const previewData: FeedbackListResponse = { data: [{ id: 'virtual-feedback-001', case_id: 'virtual-case-001', profile_version: 1, resource_type: 'query_run', resource_id: 'virtual-run-001', location_key: 'risk-card:RISK-001', error_type: 'citation_error', description_safe: '虚构反馈：请复核引用条款。', status: 'submitted', linked_knowledge_object_id: null, resolution_safe: null, submitted_by: 'virtual-consultant', handled_by: null, version_no: 1, submitted_at: '2026-09-01T00:00:00Z', resolved_at: null }], meta: { request_id: 'preview-only' } };

export function FeedbackPage() {
  const token = getAccessToken(); const navigate = useNavigate(); const client = useQueryClient(); const [params] = useSearchParams(); const preview = params.get('preview') === '1';
  const query = useQuery({ queryKey: ['feedback-items'], enabled: !preview && token !== null, retry: false, queryFn: () => { if (token === null) throw new Error('反馈不可用'); return listFeedbackItems(token); } });
  const mutation = useMutation({ mutationFn: (values: FeedbackForm) => { if (token === null) throw new Error('反馈提交不可用'); return createFeedbackItem(values, token); }, onSuccess: () => { void client.invalidateQueries({ queryKey: ['feedback-items'] }); } });
  if (!preview && token === null) return <Navigate to="/" replace />;
  const data = preview ? previewData : query.data;
  return <Layout className="app-shell"><Header className="app-header policy-header"><div><Typography.Title level={3} className="brand-title">TaxMind Pro</Typography.Title><Typography.Text className="brand-subtitle">反馈与纠错</Typography.Text></div><Button onClick={() => { void navigate(`/cases${preview ? '?preview=1' : ''}`); }}>事项工作台</Button></Header><Content className="app-content"><Space direction="vertical" size={24} className="full-width"><Alert type={preview ? 'info' : 'warning'} showIcon message={preview ? '预览模式：仅展示虚构反馈' : '仅提交脱敏事实；反馈不会直接改写正式知识'} /><Card title="提交反馈"><Form<FeedbackForm> layout="vertical" initialValues={{ resource_type: 'query_run', error_type: 'citation_error' }} onFinish={(values) => { mutation.mutate(values); }}><div className="policy-search-grid"><Form.Item label="资源类型" name="resource_type" rules={[{ required: true }]}><Select options={[{ value: 'query_run', label: '查询运行' }, { value: 'case', label: '事项' }]} /></Form.Item><Form.Item label="资源 ID" name="resource_id" rules={[{ required: true, message: '请输入可见资源 ID' }]}><Input /></Form.Item><Form.Item label="错误类型" name="error_type" rules={[{ required: true }]}><Select options={['citation_error', 'policy_scope_error', 'risk_rule_error', 'procedure_error', 'other'].map((value) => ({ value, label: value }))} /></Form.Item><Form.Item label="位置标识（可选）" name="location_key"><Input placeholder="例如 risk-card:RISK-001" /></Form.Item></div><Form.Item label="反馈说明" name="description" rules={[{ required: true, min: 3, message: '至少输入 3 个字符' }]}><Input.TextArea maxLength={1000} showCount /></Form.Item><Button type="primary" htmlType="submit" loading={mutation.isPending} disabled={preview}>提交反馈</Button>{mutation.isSuccess ? <Typography.Text type="success">反馈已提交，等待处理。</Typography.Text> : null}{mutation.isError ? <Typography.Text type="danger">反馈提交失败，请检查权限与资源范围。</Typography.Text> : null}</Form></Card><section aria-live="polite">{query.isFetching && !preview ? <Spin /> : null}{query.isError && !preview ? <Alert type="error" message="反馈列表加载失败" action={<Button onClick={() => { void query.refetch(); }}>重试</Button>} /> : null}{data?.data.length === 0 ? <Empty description="尚未提交反馈" /> : null}<List dataSource={data?.data ?? []} renderItem={(item) => <List.Item key={item.id}><Card className="full-width" title={item.error_type}><Space direction="vertical"><Space wrap><Tag color="blue">{item.status}</Tag><Tag>{item.resource_type}</Tag><Tag>版本 {item.version_no}</Tag></Space><Typography.Text>{item.description_safe}</Typography.Text><Typography.Text type="secondary">资源：{item.resource_id}</Typography.Text>{item.resolution_safe ? <Typography.Text>处理说明：{item.resolution_safe}</Typography.Text> : null}</Space></Card></List.Item>} /></section></Space></Content><Footer className="app-footer">TaxMind Pro · 内部专业辅助</Footer></Layout>;
}
